# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShopApp
  pod 'RxSwift', '6.9.0'
  pod 'RxCocoa', '6.9.0'

end
